/* AUTO-GENERATED by scripts/generate-extension-ats-recipes.ts. */
(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.HireRadarATSRecipes=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const recipes=[
  {
    "type": "greenhouse",
    "name": "Greenhouse",
    "urlPatterns": [
      "boards\\.greenhouse\\.io",
      "job-boards\\.greenhouse\\.io",
      "grnh\\.se",
      "/jobs/\\d+\\?gh_jid=",
      "/greenhouse/"
    ],
    "domSignatures": {
      "required": [
        "#application-form",
        "#application"
      ],
      "anyOf": [
        "[data-greenhouse]",
        ".greenhouse-form",
        "#greenhouse-jobboard",
        "input[name*=\"job_application\"]"
      ],
      "dataAttributes": [
        "data-job-id",
        "data-token"
      ]
    },
    "formSelectors": [
      "#application-form, #application form, form[action*=\"application\"]"
    ],
    "submitSelectors": [
      "input[type=\"submit\"], button[type=\"submit\"], button:contains(\"Submit\")"
    ],
    "successIndicators": [
      ".application-confirmation",
      "#application_confirmation",
      ".thank-you",
      "text*=\"Thank you\"",
      "text*=\"application has been received\""
    ],
    "errorIndicators": [
      ".field-error",
      ".error-message",
      ".field_with_errors",
      "[class*=\"error\"]"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "#first_name",
          "input[name=\"job_application[first_name]\"]",
          "input[name*=\"first_name\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "#last_name",
          "input[name=\"job_application[last_name]\"]",
          "input[name*=\"last_name\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "#email",
          "input[name=\"job_application[email]\"]",
          "input[type=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "#phone",
          "input[name=\"job_application[phone]\"]",
          "input[type=\"tel\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "#resume",
          "input[name=\"job_application[resume]\"]",
          "input[type=\"file\"][accept*=\"pdf\"]"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      },
      {
        "standard": "coverLetter",
        "selectors": [
          "#cover_letter",
          "input[name=\"job_application[cover_letter]\"]"
        ],
        "labelPatterns": [
          "cover letter",
          "letter of interest",
          "motivation letter"
        ],
        "inputType": "file",
        "required": false
      },
      {
        "standard": "linkedIn",
        "selectors": [
          "input[name*=\"linkedin\"]",
          "input[name*=\"answers_attributes\"][placeholder*=\"linkedin\"]"
        ],
        "labelPatterns": [
          "linkedin",
          "linkedin url",
          "linkedin profile"
        ],
        "inputType": "url",
        "required": false
      }
    ]
  },
  {
    "type": "lever",
    "name": "Lever",
    "urlPatterns": [
      "jobs\\.lever\\.co",
      "lever\\.co/jobs",
      "/lever/",
      "apply\\.lever\\.co"
    ],
    "domSignatures": {
      "required": [
        ".application-form",
        ".lever-form"
      ],
      "anyOf": [
        "[data-lever]",
        ".lever-application",
        ".posting-application",
        "form[action*=\"lever\"]"
      ],
      "dataAttributes": [
        "data-posting-id"
      ]
    },
    "formSelectors": [
      ".application-form form, .lever-form, form.application"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], button.postings-btn-submit"
    ],
    "successIndicators": [
      ".application-complete",
      ".success-page",
      "text*=\"Thanks for applying\"",
      "text*=\"Application submitted\""
    ],
    "errorIndicators": [
      ".application-error",
      ".field-error",
      "[class*=\"invalid\"]"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "fullName",
        "selectors": [
          "input[name=\"name\"]",
          "#name-input"
        ],
        "labelPatterns": [
          "full name",
          "name",
          "your name"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "input[type=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "input[type=\"tel\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload input[type=\"file\"]",
          "input[accept*=\"pdf\"]"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      },
      {
        "standard": "linkedIn",
        "selectors": [
          "input[name=\"urls[LinkedIn]\"]",
          "input[name*=\"linkedin\"]"
        ],
        "labelPatterns": [
          "linkedin",
          "linkedin url",
          "linkedin profile"
        ],
        "inputType": "url",
        "required": false
      },
      {
        "standard": "github",
        "selectors": [
          "input[name=\"urls[GitHub]\"]",
          "input[name*=\"github\"]"
        ],
        "labelPatterns": [
          "github",
          "github url",
          "github profile"
        ],
        "inputType": "url",
        "required": false
      },
      {
        "standard": "portfolio",
        "selectors": [
          "input[name=\"urls[Portfolio]\"]",
          "input[name=\"urls[Website]\"]",
          "input[name*=\"portfolio\"]"
        ],
        "labelPatterns": [
          "portfolio",
          "website",
          "personal site",
          "portfolio url"
        ],
        "inputType": "url",
        "required": false
      },
      {
        "standard": "coverLetter",
        "selectors": [
          "textarea[name=\"comments\"]",
          ".cover-letter textarea"
        ],
        "labelPatterns": [
          "additional information",
          "cover letter",
          "letter of interest",
          "motivation letter"
        ],
        "inputType": "textarea",
        "required": false
      }
    ]
  },
  {
    "type": "ashby",
    "name": "Ashby",
    "urlPatterns": [
      "jobs\\.ashbyhq\\.com",
      "\\.ashbyhq\\.com",
      "/ashby/",
      "app\\.ashbyhq\\.com"
    ],
    "domSignatures": {
      "required": [
        ".ashby-application-form"
      ],
      "anyOf": [
        "[data-ashby]",
        ".ashby-job-posting",
        "form[data-form-type=\"application\"]",
        "#ashby-embed"
      ],
      "dataAttributes": [
        "data-job-posting-id",
        "data-ashby-job-posting-id"
      ]
    },
    "formSelectors": [
      ".ashby-application-form form, form[data-form-type=\"application\"]"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], button.submit-application"
    ],
    "successIndicators": [
      ".application-success",
      ".confirmation-message",
      "text*=\"Application received\""
    ],
    "errorIndicators": [
      ".field-error",
      ".error-message",
      "[aria-invalid=\"true\"]"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"firstName\"]",
          "input[name=\"_systemfield_first_name\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"lastName\"]",
          "input[name=\"_systemfield_last_name\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "input[name=\"_systemfield_email\"]",
          "input[type=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "input[name=\"_systemfield_phone\"]",
          "input[type=\"tel\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          "input[name=\"_systemfield_resume\"]",
          "[data-field-type=\"file\"] input"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      },
      {
        "standard": "linkedIn",
        "selectors": [
          "input[name=\"linkedInUrl\"]",
          "input[name=\"_systemfield_linkedin\"]"
        ],
        "labelPatterns": [
          "linkedin",
          "linkedin url",
          "linkedin profile"
        ],
        "inputType": "url",
        "required": false
      },
      {
        "standard": "currentCompany",
        "selectors": [
          "input[name=\"currentCompany\"]",
          "input[name=\"_systemfield_current_company\"]"
        ],
        "labelPatterns": [
          "current company",
          "company"
        ],
        "inputType": "text",
        "required": false
      }
    ]
  },
  {
    "type": "workday",
    "name": "Workday",
    "urlPatterns": [
      "\\.myworkdayjobs\\.com",
      "\\.wd\\d+\\.myworkdayjobs\\.com",
      "workday\\.com/.*careers",
      "/workday/"
    ],
    "domSignatures": {
      "required": [
        "[data-automation-id]"
      ],
      "anyOf": [
        ".WGDC",
        ".WPF",
        "[data-automation-id=\"jobPostingPage\"]",
        "[data-automation-id=\"applyButton\"]"
      ],
      "dataAttributes": [
        "data-automation-id",
        "data-uxi-widget-type"
      ]
    },
    "formSelectors": [
      "[data-automation-id=\"jobApplicationForm\"]"
    ],
    "submitSelectors": [
      "[data-automation-id=\"bottom-navigation-next-button\"], [data-automation-id=\"submitButton\"]"
    ],
    "successIndicators": [
      "[data-automation-id=\"applicationSubmittedPage\"]",
      "text*=\"Application submitted\"",
      "text*=\"Thank you for applying\""
    ],
    "errorIndicators": [
      "[data-automation-id=\"errorMessage\"]",
      ".validation-error",
      "[role=\"alert\"]"
    ],
    "automationDifficulty": 5,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "[data-automation-id=\"legalNameSection_firstName\"]",
          "input[data-automation-id*=\"firstName\"]"
        ],
        "labelPatterns": [
          "legal first name",
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "[data-automation-id=\"legalNameSection_lastName\"]",
          "input[data-automation-id*=\"lastName\"]"
        ],
        "labelPatterns": [
          "legal last name",
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "[data-automation-id=\"email\"]",
          "input[data-automation-id*=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "[data-automation-id=\"phone-number\"]",
          "[data-automation-id=\"phoneNumber\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "[data-automation-id=\"file-upload-input-ref\"]",
          "input[data-automation-id*=\"resume\"]"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      },
      {
        "standard": "address",
        "selectors": [
          "[data-automation-id=\"addressSection_addressLine1\"]",
          "input[data-automation-id*=\"address\"]"
        ],
        "labelPatterns": [
          "street address",
          "address line 1",
          "address"
        ],
        "inputType": "text",
        "required": false
      },
      {
        "standard": "country",
        "selectors": [
          "[data-automation-id=\"addressSection_countryRegion\"]",
          "[data-automation-id*=\"country\"]"
        ],
        "labelPatterns": [
          "country",
          "country/region"
        ],
        "inputType": "select",
        "required": false
      }
    ]
  },
  {
    "type": "jobvite",
    "name": "Jobvite",
    "urlPatterns": [
      "jobs\\.jobvite\\.com",
      "\\.jobvite\\.com/.*apply",
      "/jobvite/"
    ],
    "domSignatures": {
      "required": [
        "#jv-application-form"
      ],
      "anyOf": [
        ".jv-page-body",
        ".jv-header",
        "[class*=\"jobvite\"]"
      ],
      "dataAttributes": [
        "data-jv-app",
        "data-jv-job-id"
      ]
    },
    "formSelectors": [
      "#jv-application-form, form.jv-apply-form"
    ],
    "submitSelectors": [
      "#jv-submit-btn, button[type=\"submit\"]"
    ],
    "successIndicators": [
      ".jv-confirmation",
      ".jv-success",
      "text*=\"Application submitted\""
    ],
    "errorIndicators": [
      ".jv-error",
      ".jv-field-error",
      "[class*=\"error\"]"
    ],
    "automationDifficulty": 3,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "#jv-firstName",
          "input[name=\"firstName\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "#jv-lastName",
          "input[name=\"lastName\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "#jv-email",
          "input[name=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "#jv-phone",
          "input[name=\"phone\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "#jv-resume",
          "input[name=\"resume\"]"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "icims",
    "name": "iCIMS",
    "urlPatterns": [
      "careers-.*\\.icims\\.com",
      "\\.icims\\.com",
      "/icims/"
    ],
    "domSignatures": {
      "required": [
        "#icims_content"
      ],
      "anyOf": [
        ".iCIMS_MainWrapper",
        ".iCIMS_JobContent",
        "[class*=\"icims\"]"
      ],
      "dataAttributes": []
    },
    "formSelectors": [
      "#icims_content form, form.iCIMS_Form"
    ],
    "submitSelectors": [
      "input[type=\"submit\"], button[type=\"submit\"]"
    ],
    "successIndicators": [
      ".iCIMS_Confirmation",
      "text*=\"Thank you\""
    ],
    "errorIndicators": [
      ".iCIMS_Error",
      "[class*=\"error\"]"
    ],
    "automationDifficulty": 4,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"firstName\"]",
          "#firstName"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"lastName\"]",
          "#lastName"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "#email"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "resume",
        "selectors": [
          "input[type=\"file\"]",
          "#resume"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "taleo",
    "name": "Taleo",
    "urlPatterns": [
      "\\.taleo\\.net",
      "taleo\\.com",
      "/taleo/"
    ],
    "domSignatures": {
      "required": [
        "#requisitionDescriptionInterface"
      ],
      "anyOf": [
        ".ftlEditFormWrapper",
        ".contentTitle",
        "[class*=\"taleo\"]"
      ],
      "dataAttributes": []
    },
    "formSelectors": [
      "#requisitionDescriptionInterface form"
    ],
    "submitSelectors": [
      "input[type=\"submit\"], .submitBtn"
    ],
    "successIndicators": [
      ".confirmationMessage",
      "text*=\"Application submitted\""
    ],
    "errorIndicators": [
      ".errorText",
      ".ftlValidationError"
    ],
    "automationDifficulty": 5,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[id*=\"FirstName\"]",
          "input[name*=\"FirstName\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[id*=\"LastName\"]",
          "input[name*=\"LastName\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[id*=\"Email\"]",
          "input[name*=\"Email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      }
    ]
  },
  {
    "type": "smartrecruiters",
    "name": "SmartRecruiters",
    "urlPatterns": [
      "jobs\\.smartrecruiters\\.com",
      "\\.smartrecruiters\\.com",
      "/smartrecruiters/"
    ],
    "domSignatures": {
      "required": [
        ".sr-job-application"
      ],
      "anyOf": [
        "[data-sr]",
        ".sr-job-details",
        "#smart-recruiters-frame"
      ],
      "dataAttributes": [
        "data-job-id",
        "data-company-id"
      ]
    },
    "formSelectors": [
      ".sr-job-application form, form.application-form"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], .apply-button"
    ],
    "successIndicators": [
      ".application-success",
      ".confirmation-screen",
      "text*=\"Thank you\""
    ],
    "errorIndicators": [
      ".error-message",
      ".validation-error"
    ],
    "automationDifficulty": 3,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"firstName\"]",
          "input[id=\"firstName\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"lastName\"]",
          "input[id=\"lastName\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "input[type=\"email\"]"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phoneNumber\"]",
          "input[type=\"tel\"]"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload input"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "bamboohr",
    "name": "BambooHR",
    "urlPatterns": [
      "\\.bamboohr\\.com/careers",
      "\\.bamboohr\\.com/jobs",
      "/bamboohr/"
    ],
    "domSignatures": {
      "required": [
        ".BambooHR-ATS-board"
      ],
      "anyOf": [
        "[data-bamboo]",
        ".bhr-application",
        "#BambooHR-ATS"
      ],
      "dataAttributes": []
    },
    "formSelectors": [
      ".bhr-application form, form.application-form"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], .submit-btn"
    ],
    "successIndicators": [
      ".thank-you",
      ".success-message",
      "text*=\"Thank you\""
    ],
    "errorIndicators": [
      ".error",
      ".validation-error"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"first_name\"]",
          "#first_name"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"last_name\"]",
          "#last_name"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "#email"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "#phone"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "breezyhr",
    "name": "BreezyHR",
    "urlPatterns": [
      "[\\w-]+\\.breezy\\.hr",
      "app\\.breezy\\.hr",
      "/breezy/"
    ],
    "domSignatures": {
      "required": [
        ".breezy-application"
      ],
      "anyOf": [
        "[data-breezy]",
        ".breezy-jobs",
        "#breezy-application-form",
        "form[action*=\"breezy\"]"
      ],
      "dataAttributes": [
        "data-position-id"
      ]
    },
    "formSelectors": [
      ".breezy-application form, #breezy-application-form"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], .submit-btn"
    ],
    "successIndicators": [
      ".thank-you",
      ".success-message",
      "text*=\"Thank you\""
    ],
    "errorIndicators": [
      ".error",
      ".validation-error"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"first_name\"]",
          "#first_name"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"last_name\"]",
          "#last_name"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "#email"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "#phone"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "jazzhr",
    "name": "JazzHR",
    "urlPatterns": [
      "[\\w-]+\\.applytojob\\.com",
      "app\\.jazz\\.co",
      "[\\w-]+\\.jazz\\.co",
      "/jazzhr/"
    ],
    "domSignatures": {
      "required": [
        ".jazz-application"
      ],
      "anyOf": [
        "[data-jazz]",
        ".jazz-jobs",
        "#jazz-application-form",
        "form[action*=\"jazz\"]",
        ".applytojob-form"
      ],
      "dataAttributes": [
        "data-job-id",
        "data-jazz-job"
      ]
    },
    "formSelectors": [
      ".jazz-application form, #jazz-application-form, .applytojob-form"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], input[type=\"submit\"]"
    ],
    "successIndicators": [
      ".confirmation",
      ".thank-you",
      "text*=\"Thank you\"",
      "text*=\"Application submitted\""
    ],
    "errorIndicators": [
      ".error",
      ".field-error"
    ],
    "automationDifficulty": 3,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"first_name\"]",
          "#first_name",
          "input[name=\"fname\"]"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"last_name\"]",
          "#last_name",
          "input[name=\"lname\"]"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "#email"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "#phone"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload",
          "input[type=\"file\"]"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      }
    ]
  },
  {
    "type": "recruitee",
    "name": "Recruitee",
    "urlPatterns": [
      "[\\w-]+\\.recruitee\\.com",
      "careers\\.recruitee\\.com",
      "/recruitee/"
    ],
    "domSignatures": {
      "required": [
        ".recruitee-careers"
      ],
      "anyOf": [
        "[data-recruitee]",
        ".recruitee-application",
        "#recruitee-form",
        "form[action*=\"recruitee\"]"
      ],
      "dataAttributes": [
        "data-offer-id"
      ]
    },
    "formSelectors": [
      ".recruitee-application form, #recruitee-form"
    ],
    "submitSelectors": [
      "button[type=\"submit\"], .apply-button"
    ],
    "successIndicators": [
      ".success",
      ".thank-you",
      "text*=\"Thank you\""
    ],
    "errorIndicators": [
      ".error",
      ".validation-error"
    ],
    "automationDifficulty": 2,
    "fieldMappings": [
      {
        "standard": "firstName",
        "selectors": [
          "input[name=\"first_name\"]",
          "#first_name"
        ],
        "labelPatterns": [
          "first name",
          "given name",
          "first"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "lastName",
        "selectors": [
          "input[name=\"last_name\"]",
          "#last_name"
        ],
        "labelPatterns": [
          "last name",
          "family name",
          "surname",
          "last"
        ],
        "inputType": "text",
        "required": true
      },
      {
        "standard": "email",
        "selectors": [
          "input[name=\"email\"]",
          "#email"
        ],
        "labelPatterns": [
          "email",
          "e-mail",
          "email address"
        ],
        "inputType": "email",
        "required": true
      },
      {
        "standard": "phone",
        "selectors": [
          "input[name=\"phone\"]",
          "#phone"
        ],
        "labelPatterns": [
          "phone",
          "telephone",
          "mobile",
          "cell",
          "phone number"
        ],
        "inputType": "tel",
        "required": false
      },
      {
        "standard": "resume",
        "selectors": [
          "input[name=\"resume\"]",
          ".resume-upload"
        ],
        "labelPatterns": [
          "resume",
          "cv",
          "curriculum vitae",
          "upload resume"
        ],
        "inputType": "file",
        "required": true
      },
      {
        "standard": "linkedIn",
        "selectors": [
          "input[name=\"linkedin\"]",
          "#linkedin"
        ],
        "labelPatterns": [
          "linkedin",
          "linkedin url",
          "linkedin profile"
        ],
        "inputType": "url",
        "required": false
      }
    ]
  }
];
  const detect=(url)=>{const value=String(url||'');return recipes.find((recipe)=>recipe.urlPatterns.some((pattern)=>{try{return new RegExp(pattern,'i').test(value);}catch{return false;}}))||null;};
  return {recipes,detect};
});
