import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { ATS_REGISTRY } from '../src/lib/ats-registry';

const recipes = Object.values(ATS_REGISTRY)
  .filter((config) => config.type !== 'unknown')
  .map((config) => ({
    type: config.type,
    name: config.name,
    urlPatterns: config.urlPatterns,
    domSignatures: config.domSignatures,
    formSelectors: [config.formPatterns.formSelector].filter(Boolean),
    submitSelectors: [config.formPatterns.submitSelector].filter(Boolean),
    successIndicators: config.formPatterns.successIndicators,
    errorIndicators: config.formPatterns.errorIndicators,
    automationDifficulty: config.automationDifficulty,
    fieldMappings: config.fieldMappings.map((field) => ({
      standard: field.standard,
      selectors: field.selectors,
      labelPatterns: field.labelPatterns,
      inputType: field.inputType,
      required: field.required,
    })),
  }));

const output = `/* AUTO-GENERATED by scripts/generate-extension-ats-recipes.ts. */\n`
  + `(function(root,factory){const api=factory();if(typeof module!=='undefined'&&module.exports)module.exports=api;root.HireRadarATSRecipes=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){\n`
  + `  const recipes=${JSON.stringify(recipes, null, 2)};\n`
  + `  const detect=(url)=>{const value=String(url||'');return recipes.find((recipe)=>recipe.urlPatterns.some((pattern)=>{try{return new RegExp(pattern,'i').test(value);}catch{return false;}}))||null;};\n`
  + `  return {recipes,detect};\n});\n`;

writeFileSync(resolve(process.cwd(), 'extension/ats-recipes.js'), output, 'utf8');
console.log(`Generated ${recipes.length} browser ATS recipes.`);